### PR TITLE
Setup for Travis CI and Codecov

### LINKED ISSUE #35: Set up Travis and CodeCov integration
Me or @fingolfin could hopefully help with that.

### PR DESCRIPTION
**Pull request by alex-konovalov**
This sets up tools which will run tests for every change suggested in the package to check that they still run correctly after the change and calculate code coverage. Closes #35.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
The CI setup works, but the test fails because 32-buit build fails - interested to know why.

**Comment by alex-konovalov** [comment]
About 32-bit build: on Jenkins, it builds fine under macOS and Scientific Linux.

**Comment by fingolfin** [comment]
@alex-konovalov the problem is that the guava build system does not honor the environment variables CFLAGS; `Makefile.in` overrides it with `-O2`. Hence `-m32` is not passed to the compiler, only to the linker.

**Comment by alex-konovalov** [comment]
Then I suggest to merge it, and this will help to test the updates for build process and other changes later.

**Comment by alex-konovalov** [comment]
@dimpase if you merge this first, then you will be able to submit a PR addressing #31 and test it on Travis, so I think it's the other way round.

**Comment by alex-konovalov** [comment]
@osj1961 @wdjoyner I haven't hear back regarding GUAVA for a while - I will take the liberty to merge this so we can work on the new PRs efficiently, as this PR does not change any mathematical functionality of the package. If you will have any questions/comments/changes please let me know.

**Pull request merged**
